# Generated by Django 4.1 on 2022-09-09 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_livro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livro',
            old_name='título',
            new_name='titulo',
        ),
    ]
